### ISSUE TITLE
百度网盘失效了，求分享到邮箱1754133505@qq.com

### ISSUE THREAD

**Issue by pppyj-m** [xiaolei565/aimto408#15]

**Comment by xiaolei565** [comment]
请查收，邮箱也分享了
链接：https://pan.baidu.com/s/1V9K4pZFN61SZW7SYZy5PgQ 
提取码：2022

**Comment by ac-computer** [comment]
网盘失效了，求分享到邮箱1193976968@qq.com，感谢大佬！
