### ISSUE TITLE
阿里云网盘失效

### ISSUE THREAD

**Issue by ZoeSj** [xiaolei565/aimto408#18]
还有有效的阿里云盘资源吗？

**Comment by xiaolei565** [comment]
最新链接已更新
链接：https://www.aliyundrive.com/s/3S2hyaz4RFu

**Comment by jerrita** [comment]
> 最新链接已更新
> 链接：https://www.aliyundrive.com/s/3S2hyaz4RFu

已失效

**Comment by xiaolei565** [comment]
🔗已更新：阿里云盘 ：https://www.aliyundrive.com/s/wdeBS6RaXZm  提取码: 89ua 

 @jerrita
